### ISSUE TITLE
How can we replay the trained model?

### ISSUE THREAD

**Issue by Suguru55** [lancerane/NIPS-2018-AI-for-Prosthetics#2]
After the training process in main.py, I obtained ProstheticsEnv_R2_multiclip_after_XX.model.meta files. 
How should I do for checking the training parameters?

**Comment by lancerane** [comment]
At the bottom of main.py, change

train(5000000, 999, save_model_with_prefix=True, restore_model_from_file=False, save_after=14, load_after_iters=100, viz=False, stochastic=True)

to:

train(5000000, 999, save_model_with_prefix=True, restore_model_from_file=True, save_after=14, load_after_iters=XX, viz=False, stochastic=True)

to resume training from the XX checkpoint

**Comment by Suguru55** [comment]
Thanks. I could resume training from the XX checkpoint. But, it continues training process. Only to check the performance of XX checkpoint, I need to change learn function in pposgd_simple.py, right?

**Comment by lancerane** [comment]
If you change 'stochastic' to False, run on one worker and set the timesteps parameter appropriately, you'll get a fairly good estimate of performance over that no. of timesteps, before the first update. Note that this is currently for 890 timesteps per episode: it's limited by the length of one of the motion clips. You can increase this in the ProstheticsEnv_R2_multiclip class in osim/env/osim.py.

To get a better estimate, you need to turn off random state and velocity initialisation, by changing the 'test' parameter in env.reset(), in pposgd_simple.py, to true:

ob = env.reset(test=True) . There are two occurrences in traj_segment_generator().

To make it completely equivalent to the test environment, you also need to change the integrator back to default, which can be done by changing the reset_manager() function at the top of osim.py to the commented version. In practise this has minimal impact.

**Comment by Suguru55** [comment]
I changed 'test' parameter in pposgd_simple.py and restarted training process just before.
After the process, I will try to change 'stochastic' to False, no. of timesteps in osim.py, and the reset_manager() function at the top of osim.py to the commented version for displaying the learning result.

**Comment by Suguru55** [comment]
I changed  'stochastic' to False, no. of timesptes, and the 'test' parameter in env.reset(), in pposgd_simple.py, to true.
After that, I could replay the trained model, thanks!
